import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Category } from '../models/category.model';
import { environment } from '../../enviroments/enviroment';
import { Observable } from 'rxjs';

@Injectable({ providedIn: 'root' })
export class CategoriesService {
  private base = `${environment.apiUrl}/categories`;

  constructor(private http: HttpClient) {}

  getAll(): Observable<Category[]> {
    return this.http.get<Category[]>(this.base);
  }

  create(category: Partial<Category>): Observable<Category> {
    // Some servers require the id to be autogenerated; if your server expects
    // an id generated on the client, add logic here. For now we POST the provided payload.
    return this.http.post<Category>(this.base, category);
  }

  update(category: Category): Observable<Category> {
    return this.http.put<Category>(`${this.base}/${category.id}`, category);
  }

  delete(id: number): Observable<void> {
    return this.http.delete<void>(`${this.base}/${id}`);
  }
}
